name: Quarkus Functions
version: 0.0.3
description: Quarkus function runtime for cloud event services
license: Apache-2.0
language: java
maintainers:
  - name: Lance Ball
    email: lball@redhat.com
    github-id: lance
  - name: Matej Vasek
    email: mvasek@redhat.com
    github-id: matejvasek
default-template: default
requirements:
   appsody-version: ">= 0.6.0"
